In [1]:
import pandas as pd

In [2]:
Player=pd.read_excel(r'C:\Users\USER\OneDrive\Documents\ds_c8_datafiles-main\players.xlsx')
Game=pd.read_excel(r'C:\Users\USER\OneDrive\Documents\ds_c8_datafiles-main\games.xlsx')
Game_event=pd.read_excel(r'C:\Users\USER\OneDrive\Documents\ds_c8_datafiles-main\game_events.xlsx')
Game_line=pd.read_excel(r'C:\Users\USER\OneDrive\Documents\ds_c8_datafiles-main\game_lineups.xlsx')
Appe=pd.read_excel(r'C:\Users\USER\OneDrive\Documents\ds_c8_datafiles-main\appearances.xlsx')

In [3]:
FootBall_data=pd.merge(Appe,Game_event,on='game_id',how='outer')
FootBall_data=pd.merge(FootBall_data,Game_line,on='game_id',how='outer')
FootBall_data=pd.merge(FootBall_data,Game,on='game_id',how='outer')
FootBall_data=pd.merge(FootBall_data,Player,on='player_id',how='outer')

In [5]:
FootBall_data

,appearance_id,game_id,player_id_x,date_x,player_name_x,competition_id_x,yellow_cards,red_cards,goals,assists,...,country_of_birth,date_of_birth,sub_position,position_y,foot,height_in_cm,market_value_in_eur,highest_market_value_in_eur,contract_expiration_date,agent_name
0,2224728_119169,2224728.0,119169.0,2012-07-13,Aron Johannsson,DK1,0.0,0.0,0.0,0.0,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
1,2224732_161244,2224732.0,161244.0,2012-07-14,Conor O'Brien,DK1,0.0,0.0,1.0,0.0,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
2,2224729_39467,2224729.0,39467.0,2012-07-15,Clarence Goodson,DK1,0.0,0.0,0.0,0.0,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
3,2232104_119169,2232104.0,119169.0,2012-07-19,Aron Johannsson,ELQ,0.0,0.0,0.0,0.0,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
4,2219794_39475,2219794.0,39475.0,2012-07-22,Sacha Kljestan,BESC,0.0,0.0,0.0,0.0,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4806,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,United States,1997-08-06,Defensive Midfield,Midfield,right,193.0,4000000.0,4000000.0,NaT,NaN
4807,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,United States,2001-09-24,Central Midfield,Midfield,right,188.0,2000000.0,2500000.0,2025-06-30,PROSPORT Management
4808,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,United States,1987-04-29,Central Midfield,Midfield,right,182.0,300000.0,2500000.0,2023-12-31,YMU Group
4809,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,United States,1992-09-16,Left Winger,Attack,both,175.0,400000.0,600000.0,2023-12-31,BR Group Management
4810,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,United States,1971-05-18,Goalkeeper,Goalkeeper,NaN,NaN,NaN,4000000.0,NaT,NaN

In [4]:
FootBall_data.isnull().sum()

appearance_id                  1002
game_id                         125
player_id_x                    1002
date_x                         1002
player_name_x                  1002
competition_id_x               1002
yellow_cards                   1002
red_cards                      1002
goals                          1002
assists                        1002
minutes_played                 1002
game_event_id                  2727
date_y                         2727
minute                         2727
type_x                         2727
player_id_y                    2727
description                    3742
player_in_id                   3519
player_assist_id               4644
game_lineups_id                4567
type_y                         4567
number                         4567
player_id                      4442
player_name_y                  4567
team_captain                   4567
position_x                     4567
competition_id_y               1002
season                         1002
round                          1002
date                           1002
home_club_goals                1002
away_club_goals                1002
home_club_position             1552
away_club_position             1552
home_club_manager_name         1008
away_club_manager_name         1008
stadium                        1002
attendance                     1143
referee                        1007
home_club_formation            4811
away_club_formation            4811
home_club_name                 1130
away_club_name                 1070
aggregate                      1002
competition_type               1002
name                           4442
last_season                    4442
current_club_id                4442
player_code                    4442
country_of_birth               4442
date_of_birth                  4442
sub_position                   4442
position_y                     4442
foot                           4453
height_in_cm                   4445
market_value_in_eur            4480
highest_market_value_in_eur    4446
contract_expiration_date       4496
agent_name                     4554
dtype: int64

In [6]:
for col in FootBall_data.columns:
    if FootBall_data[col].dtypes=='object':
        FootBall_data[col].fillna(FootBall_data[col].mode()[0],inplace=True)
    else:
        FootBall_data[col].fillna(FootBall_data[col].mean(),inplace=True)

In [9]:
FootBall_data.isnull().sum()

appearance_id                  0
game_id                        0
player_id_x                    0
date_x                         0
player_name_x                  0
competition_id_x               0
yellow_cards                   0
red_cards                      0
goals                          0
assists                        0
minutes_played                 0
game_event_id                  0
date_y                         0
minute                         0
type_x                         0
player_id_y                    0
description                    0
player_in_id                   0
player_assist_id               0
game_lineups_id                0
type_y                         0
number                         0
player_id                      0
player_name_y                  0
team_captain                   0
position_x                     0
competition_id_y               0
season                         0
round                          0
date                           0
home_club_goals                0
away_club_goals                0
home_club_position             0
away_club_position             0
home_club_manager_name         0
away_club_manager_name         0
stadium                        0
attendance                     0
referee                        0
home_club_name                 0
away_club_name                 0
aggregate                      0
competition_type               0
name                           0
last_season                    0
current_club_id                0
player_code                    0
country_of_birth               0
date_of_birth                  0
sub_position                   0
position_y                     0
foot                           0
height_in_cm                   0
market_value_in_eur            0
highest_market_value_in_eur    0
contract_expiration_date       0
agent_name                     0
dtype: int64

In [8]:
FootBall_data.drop(columns=['home_club_formation'],inplace=True)
FootBall_data.drop(columns=['away_club_formation'],inplace=True)

In [10]:
FootBall_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4811 entries, 0 to 4810
Data columns (total 57 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   appearance_id                4811 non-null   object
 1   game_id                      4811 non-null   float64
 2   player_id_x                  4811 non-null   float64
 3   date_x                       4811 non-null   datetime64[ns]
 4   player_name_x                4811 non-null   object
 5   competition_id_x             4811 non-null   object
 6   yellow_cards                 4811 non-null   float64
 7   red_cards                    4811 non-null   float64
 8   goals                        4811 non-null   float64
 9   assists                      4811 non-null   float64
 10  minutes_played               4811 non-null   float64
 11  game_event_id                4811 non-null   object
 12  date_y                       4811 non-null   datetime64[ns]
 13  minute                       4811 non-null   float64
 14  type_x                       4811 non-null   object
 15  player_id_y                  4811 non-null   float64
 16  description                  4811 non-null   object
 17  player_in_id                 4811 non-null   float64
 18  player_assist_id             4811 non-null   float64
 19  game_lineups_id              4811 non-null   object
 20  type_y                       4811 non-null   object
 21  number                       4811 non-null   float64
 22  player_id                    4811 non-null   float64
 23  player_name_y                4811 non-null   object
 24  team_captain                 4811 non-null   float64
 25  position_x                   4811 non-null   object
 26  competition_id_y             4811 non-null   object
 27  season                       4811 non-null   float64
 28  round                        4811 non-null   object
 29  date                         4811 non-null   datetime64[ns]
 30  home_club_goals              4811 non-null   float64
 31  away_club_goals              4811 non-null   float64
 32  home_club_position           4811 non-null   float64
 33  away_club_position           4811 non-null   float64
 34  home_club_manager_name       4811 non-null   object
 35  away_club_manager_name       4811 non-null   object
 36  stadium                      4811 non-null   object
 37  attendance                   4811 non-null   float64
 38  referee                      4811 non-null   object
 39  home_club_name               4811 non-null   object
 40  away_club_name               4811 non-null   object
 41  aggregate                    4811 non-null   object
 42  competition_type             4811 non-null   object
 43  name                         4811 non-null   object
 44  last_season                  4811 non-null   float64
 45  current_club_id              4811 non-null   float64
 46  player_code                  4811 non-null   object
 47  country_of_birth             4811 non-null   object
 48  date_of_birth                4811 non-null   datetime64[ns]
 49  sub_position                 4811 non-null   object
 50  position_y                   4811 non-null   object
 51  foot                         4811 non-null   object
 52  height_in_cm                 4811 non-null   float64
 53  market_value_in_eur          4811 non-null   float64
 54  highest_market_value_in_eur  4811 non-null   float64
 55  contract_expiration_date     4811 non-null   datetime64[ns]
 56  agent_name                   4811 non-null   object
dtypes: datetime64[ns](5), float64(25), object(27)
memory usage: 2.1+ MB

In [14]:
FootBall_data[FootBall_data.duplicated()]

Empty DataFrame
Columns: [appearance_id, game_id, player_id_x, date_x, player_name_x, competition_id_x, yellow_cards, red_cards, goals, assists, minutes_played, game_event_id, date_y, minute, type_x, player_id_y, description, player_in_id, player_assist_id, game_lineups_id, type_y, number, player_id, player_name_y, team_captain, position_x, competition_id_y, season, round, date, home_club_goals, away_club_goals, home_club_position, away_club_position, home_club_manager_name, away_club_manager_name, stadium, attendance, referee, home_club_name, away_club_name, aggregate, competition_type, name, last_season, current_club_id, player_code, country_of_birth, date_of_birth, sub_position, position_y, foot, height_in_cm, market_value_in_eur, highest_market_value_in_eur, contract_expiration_date, agent_name]
Index: []

[0 rows x 57 columns]

In [11]:
FootBall_data.to_excel("Football_cleaned_data.xlsx",index=False)
from IPython.display import FileLink
FileLink('Football_cleaned_data.xlsx')

C:\Users\USER\OneDrive\Kowsalya R_Capstone_Project\Football_cleaned_data.xlsx

In [12]:
FootBall_data.to_csv("Football",index=False)
from IPython.display import FileLink
FileLink('Football')

C:\Users\USER\OneDrive\Kowsalya R_Capstone_Project\Football